export const COMPONENT_USAGE_THEME_LIGHT = 'light';
export const COMPONENT_USAGE_THEME_DARK = 'dark';
export const COMPONENT_USAGE_THEME_NEUTRAL = 'neutral';
export const COMPONENT_USAGE_ACCEPTABLE_THEMES = [
  COMPONENT_USAGE_THEME_LIGHT,
  COMPONENT_USAGE_THEME_DARK,
  COMPONENT_USAGE_THEME_NEUTRAL
];
